/******************************************************************************/
/*                 Generated by IBExpert 12/11/2019 04:36:49                  */
/******************************************************************************/

/******************************************************************************/
/*        Following SET SQL DIALECT is just for the Database Comparer         */
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/*                                   Tables                                   */
/******************************************************************************/


CREATE GENERATOR SEQ_DISTRIBUIDORES;

CREATE TABLE DISTRIBUIDORES (
    DISTRIBUIDOR_ID  INTEGER NOT NULL,
    NOME             VARCHAR(50) NOT NULL,
    INSCRICAO        CHAR(1) NOT NULL,
    CPF_CNPJ         VARCHAR(18) NOT NULL
);




/******************************************************************************/
/*                             Check constraints                              */
/******************************************************************************/

ALTER TABLE DISTRIBUIDORES ADD CONSTRAINT CK_INSCRICAO_DISTRIBUIDORES check (INSCRICAO IN ('F','J'));


/******************************************************************************/
/*                                Primary keys                                */
/******************************************************************************/

ALTER TABLE DISTRIBUIDORES ADD CONSTRAINT PK_DISTRIBUIDORES PRIMARY KEY (DISTRIBUIDOR_ID);


/******************************************************************************/
/*                                  Triggers                                  */
/******************************************************************************/



SET TERM ^ ;



/******************************************************************************/
/*                            Triggers for tables                             */
/******************************************************************************/



/* Trigger: DISTRIBUIDORES_IU_BR */
CREATE OR ALTER TRIGGER DISTRIBUIDORES_IU_BR FOR DISTRIBUIDORES
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.DISTRIBUIDOR_ID IS NULL) THEN
    NEW.DISTRIBUIDOR_ID = GEN_ID(SEQ_DISTRIBUIDORES,1);
END
^

SET TERM ; ^



/******************************************************************************/
/*                                 Privileges                                 */
/******************************************************************************/
