/******************************************************************************/
/*                 Generated by IBExpert 12/11/2019 04:36:35                  */
/******************************************************************************/

/******************************************************************************/
/*        Following SET SQL DIALECT is just for the Database Comparer         */
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/*                                   Tables                                   */
/******************************************************************************/



CREATE TABLE LIMITE_CREDITOS (
    PRODUTOR_ID      INTEGER NOT NULL,
    LIMITE_CREDITO   NUMERIC(10,2) NOT NULL,
    DISTRIBUIDOR_ID  INTEGER NOT NULL
);




/******************************************************************************/
/*                             Check constraints                              */
/******************************************************************************/

ALTER TABLE LIMITE_CREDITOS ADD CONSTRAINT CK_LIM_CRED_INSCRICAO check (LIMITE_CREDITO >= 0);


/******************************************************************************/
/*                                Primary keys                                */
/******************************************************************************/

ALTER TABLE LIMITE_CREDITOS ADD CONSTRAINT PK_LIMITE_CREDITOS PRIMARY KEY (PRODUTOR_ID, DISTRIBUIDOR_ID);


/******************************************************************************/
/*                                Foreign keys                                */
/******************************************************************************/

ALTER TABLE LIMITE_CREDITOS ADD CONSTRAINT FK_LIMITE_CREDITOS_DISTRIBUIDOR FOREIGN KEY (DISTRIBUIDOR_ID) REFERENCES DISTRIBUIDORES (DISTRIBUIDOR_ID);
ALTER TABLE LIMITE_CREDITOS ADD CONSTRAINT FK_LIMITE_CREDITOS_PRODUTOR FOREIGN KEY (PRODUTOR_ID) REFERENCES PRODUTORES (PRODUTOR_ID);


/******************************************************************************/
/*                                 Privileges                                 */
/******************************************************************************/
