/******************************************************************************/
/*                 Generated by IBExpert 12/11/2019 04:36:22                  */
/******************************************************************************/

/******************************************************************************/
/*        Following SET SQL DIALECT is just for the Database Comparer         */
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/*                                   Tables                                   */
/******************************************************************************/


CREATE GENERATOR SEQ_NEGOCIACOES;

CREATE TABLE NEGOCIACOES (
    NEGOCIACAO_ID    INTEGER NOT NULL,
    DATA_NEGOCIACAO  TIMESTAMP NOT NULL,
    PRODUTOR_ID      INTEGER NOT NULL,
    DISTRIBUIDOR_ID  INTEGER NOT NULL,
    PRODUTO_ID       INTEGER NOT NULL,
    QUANTIDADE       NUMERIC(10,2) NOT NULL,
    PRECO_VENDA      NUMERIC(10,2) NOT NULL,
    TOTAL            NUMERIC(10,2) NOT NULL
);




/******************************************************************************/
/*                             Check constraints                              */
/******************************************************************************/

ALTER TABLE NEGOCIACOES ADD CONSTRAINT CHK_NEGOCIACOES_QUANTIDADE CHECK (QUANTIDADE >= 0);
ALTER TABLE NEGOCIACOES ADD CONSTRAINT CHK_NEGOCIACOES_PRECO_VENDA CHECK (PRECO_VENDA >= 0);
ALTER TABLE NEGOCIACOES ADD CONSTRAINT CHK_NEGOCIACOES_TOTAL CHECK (TOTAL >= 0);


/******************************************************************************/
/*                                Primary keys                                */
/******************************************************************************/

ALTER TABLE NEGOCIACOES ADD CONSTRAINT PK_NEGOCIACOES PRIMARY KEY (NEGOCIACAO_ID);


/******************************************************************************/
/*                                Foreign keys                                */
/******************************************************************************/

ALTER TABLE NEGOCIACOES ADD CONSTRAINT FK_NEGOCIACOES_DISTRIBUIDOR FOREIGN KEY (DISTRIBUIDOR_ID) REFERENCES DISTRIBUIDORES (DISTRIBUIDOR_ID);
ALTER TABLE NEGOCIACOES ADD CONSTRAINT FK_NEGOCIACOES_PRODUTO FOREIGN KEY (PRODUTO_ID) REFERENCES PRODUTOS (PRODUTO_ID);
ALTER TABLE NEGOCIACOES ADD CONSTRAINT FK_NEGOCIACOES_PRODUTOR FOREIGN KEY (PRODUTOR_ID) REFERENCES PRODUTORES (PRODUTOR_ID);


/******************************************************************************/
/*                                  Triggers                                  */
/******************************************************************************/



SET TERM ^ ;



/******************************************************************************/
/*                            Triggers for tables                             */
/******************************************************************************/



/* Trigger: NEGOCIACOES_IU_BR */
CREATE OR ALTER TRIGGER NEGOCIACOES_IU_BR FOR NEGOCIACOES
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.NEGOCIACAO_ID IS NULL) THEN
    NEW.NEGOCIACAO_ID = GEN_ID(SEQ_NEGOCIACOES, 1);
END
^

SET TERM ; ^



/******************************************************************************/
/*                                 Privileges                                 */
/******************************************************************************/
